version: '3.7'
services:
  app:
    command: npm run start:dev
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    network:
      - mynetwork
  
  postgresql:
    image: postgres:15
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOSTNAME: ${DB_HOSTNAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    network:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    env_file:
      - .env
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgresql
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
    user: "root"
    network:
      - mynetwork

networks:
  mynetwork